"""001 initial inventory domain

Revision ID: 4d7350a11464
Revises:
Create Date: 2026-09-21 16:27:52.336734

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4d7350a11464'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_external_id', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_external_ref'), 'contacts', ['external_ref'], unique=False)
    op.create_table('locations',
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('products',
    sa.Column('internal_reference', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('consignment_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PEN'"), nullable=False),
    sa.Column('raw_external_id', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('internal_reference', name=op.f('uq_products_internal_reference'))
    )
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('auth_user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_user_id', name=op.f('uq_users_auth_user_id'))
    )
    op.create_table('inventory_campaigns',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'RECOUNT', 'UNDER_REVIEW', 'APPROVED', 'CLOSED', 'EXPIRED', 'CANCELLED', name='campaignstatus', native_enum=False, length=50), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by', sa.Uuid(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_inventory_campaigns_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_inventory_campaigns_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_inventory_campaigns_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], name=op.f('fk_inventory_campaigns_reopened_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_campaigns')),
    sa.UniqueConstraint('code', name=op.f('uq_inventory_campaigns_code'))
    )
    op.create_index(op.f('ix_inventory_campaigns_deadline_at'), 'inventory_campaigns', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_inventory_campaigns_status'), 'inventory_campaigns', ['status'], unique=False)
    op.create_table('product_supplier_refs',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_reference', sa.String(length=255), nullable=True),
    sa.Column('raw_external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_product_supplier_refs_contact_id_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_supplier_refs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_supplier_refs')),
    sa.UniqueConstraint('product_id', 'contact_id', name=op.f('uq_product_supplier_refs_product_id'))
    )
    op.create_index(op.f('ix_product_supplier_refs_contact_id'), 'product_supplier_refs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_product_supplier_refs_product_id'), 'product_supplier_refs', ['product_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_audit_events_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_inventory_campaign_id'), 'audit_events', ['inventory_campaign_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('inventory_assignments',
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'COMPLETED', name='assignmentstatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_inventory_assignments_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_inventory_assignments_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_assignments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_assignments'))
    )
    op.create_index(op.f('ix_inventory_assignments_inventory_campaign_id'), 'inventory_assignments', ['inventory_campaign_id'], unique=False)
    op.create_index(op.f('ix_inventory_assignments_status'), 'inventory_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_assignments_user_id'), 'inventory_assignments', ['user_id'], unique=False)
    op.create_table('inventory_count_sessions',
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('INITIAL', 'REASSIGNMENT', 'RECOUNT', 'SUPERVISOR_CHECK', name='sessiontype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'CANCELLED', name='sessionstatus', native_enum=False, length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_identifier', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['inventory_assignments.id'], name=op.f('fk_inventory_count_sessions_assignment_id_inventory_assignments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_inventory_count_sessions_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_count_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_count_sessions')),
    sa.UniqueConstraint('inventory_campaign_id', 'session_number', name=op.f('uq_inventory_count_sessions_inventory_campaign_id'))
    )
    op.create_index(op.f('ix_inventory_count_sessions_inventory_campaign_id'), 'inventory_count_sessions', ['inventory_campaign_id'], unique=False)
    op.create_index(op.f('ix_inventory_count_sessions_user_id'), 'inventory_count_sessions', ['user_id'], unique=False)
    op.create_table('inventory_reconciliations',
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('approved_physical_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('difference_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('damaged_quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('missing_quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('surplus_quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('effective_unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('missing_cost_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('damage_cost_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('surplus_cost_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('affected_sale_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'DIFFERENCE', 'RECOUNT_REQUIRED', 'UNDER_REVIEW', 'APPROVED', name='reconciliationstatus', native_enum=False, length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_inventory_reconciliations_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_inventory_reconciliations_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_reconciliations_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reconciliations')),
    sa.UniqueConstraint('inventory_campaign_id', 'product_id', name=op.f('uq_inventory_reconciliations_inventory_campaign_id'))
    )
    op.create_index(op.f('ix_inventory_reconciliations_inventory_campaign_id'), 'inventory_reconciliations', ['inventory_campaign_id'], unique=False)
    op.create_index(op.f('ix_inventory_reconciliations_product_id'), 'inventory_reconciliations', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_reconciliations_status'), 'inventory_reconciliations', ['status'], unique=False)
    op.create_table('inventory_recounts',
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_session_id', sa.Uuid(), nullable=True),
    sa.Column('resulting_session_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_inventory_recounts_assigned_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_inventory_recounts_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_inventory_recounts_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resulting_session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_recounts_resulting_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_recounts_source_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_recounts'))
    )
    op.create_index(op.f('ix_inventory_recounts_assigned_user_id'), 'inventory_recounts', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_inventory_recounts_inventory_campaign_id'), 'inventory_recounts', ['inventory_campaign_id'], unique=False)
    op.create_table('inventory_snapshot_items',
    sa.Column('inventory_campaign_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('internal_reference_snapshot', sa.String(length=100), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sale_price_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cost_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('consignment_cost_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('effective_cost_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cost_source', sa.Enum('COST', 'CONSIGNMENT', 'ZERO', name='costsource', native_enum=False, length=50), nullable=False),
    sa.Column('currency_snapshot', sa.String(length=3), nullable=False),
    sa.Column('supplier_reference_snapshot', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_campaign_id'], ['inventory_campaigns.id'], name=op.f('fk_inventory_snapshot_items_inventory_campaign_id_inventory_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_inventory_snapshot_items_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_snapshot_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_snapshot_items'))
    )
    op.create_index(op.f('ix_inventory_snapshot_items_inventory_campaign_id'), 'inventory_snapshot_items', ['inventory_campaign_id'], unique=False)
    op.create_index('uq_inventory_snapshot_items_campaign_product_no_location', 'inventory_snapshot_items', ['inventory_campaign_id', 'product_id'], unique=True, postgresql_where=sa.text('location_id IS NULL'))
    op.create_index('uq_inventory_snapshot_items_campaign_product_location', 'inventory_snapshot_items', ['inventory_campaign_id', 'product_id', 'location_id'], unique=True, postgresql_where=sa.text('location_id IS NOT NULL'))
    op.create_table('inventory_count_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('scanned_code', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.Enum('QR_SCAN', 'MULTI_QR_SCAN', 'MANUAL_ADD', 'MANUAL_SUBTRACT', 'MANUAL_SET', 'UNDO', 'DAMAGE_ADD', 'DAMAGE_SUBTRACT', name='counteventtype', native_enum=False, length=50), nullable=False),
    sa.Column('delta_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('set_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('resulting_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.Enum('CAMERA', 'MANUAL', 'OFFLINE_SYNC', 'SYSTEM', name='eventsource', native_enum=False, length=50), nullable=False),
    sa.Column('client_event_uuid', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_count_events_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_count_events_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_count_events')),
    sa.UniqueConstraint('client_event_uuid', name=op.f('uq_inventory_count_events_client_event_uuid'))
    )
    op.create_index(op.f('ix_inventory_count_events_occurred_at'), 'inventory_count_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_count_events_product_id'), 'inventory_count_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_count_events_scanned_code'), 'inventory_count_events', ['scanned_code'], unique=False)
    op.create_index(op.f('ix_inventory_count_events_session_id'), 'inventory_count_events', ['session_id'], unique=False)
    op.create_table('inventory_count_totals',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('damaged_quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_count_totals_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_count_totals_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_count_totals')),
    sa.UniqueConstraint('session_id', 'product_id', name=op.f('uq_inventory_count_totals_session_id'))
    )
    op.create_index(op.f('ix_inventory_count_totals_product_id'), 'inventory_count_totals', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_count_totals_session_id'), 'inventory_count_totals', ['session_id'], unique=False)
    op.create_table('inventory_damages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('evidence_path', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_damages_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_damages_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_damages_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_damages'))
    )
    op.create_index(op.f('ix_inventory_damages_product_id'), 'inventory_damages', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_damages_session_id'), 'inventory_damages', ['session_id'], unique=False)
    op.create_table('inventory_extra_items',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_extra_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_extra_items_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_extra_items')),
    sa.UniqueConstraint('session_id', 'product_id', name=op.f('uq_inventory_extra_items_session_id'))
    )
    op.create_index(op.f('ix_inventory_extra_items_product_id'), 'inventory_extra_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_extra_items_session_id'), 'inventory_extra_items', ['session_id'], unique=False)
    op.create_table('inventory_unknown_codes',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('scanned_code', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_product_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_inventory_unknown_codes_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_product_id'], ['products.id'], name=op.f('fk_inventory_unknown_codes_resolved_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.id'], name=op.f('fk_inventory_unknown_codes_session_id_inventory_count_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_unknown_codes')),
    sa.UniqueConstraint('session_id', 'scanned_code', name=op.f('uq_inventory_unknown_codes_session_id'))
    )
    op.create_index(op.f('ix_inventory_unknown_codes_session_id'), 'inventory_unknown_codes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_unknown_codes_session_id'), table_name='inventory_unknown_codes')
    op.drop_table('inventory_unknown_codes')
    op.drop_index(op.f('ix_inventory_extra_items_session_id'), table_name='inventory_extra_items')
    op.drop_index(op.f('ix_inventory_extra_items_product_id'), table_name='inventory_extra_items')
    op.drop_table('inventory_extra_items')
    op.drop_index(op.f('ix_inventory_damages_session_id'), table_name='inventory_damages')
    op.drop_index(op.f('ix_inventory_damages_product_id'), table_name='inventory_damages')
    op.drop_table('inventory_damages')
    op.drop_index(op.f('ix_inventory_count_totals_session_id'), table_name='inventory_count_totals')
    op.drop_index(op.f('ix_inventory_count_totals_product_id'), table_name='inventory_count_totals')
    op.drop_table('inventory_count_totals')
    op.drop_index(op.f('ix_inventory_count_events_session_id'), table_name='inventory_count_events')
    op.drop_index(op.f('ix_inventory_count_events_scanned_code'), table_name='inventory_count_events')
    op.drop_index(op.f('ix_inventory_count_events_product_id'), table_name='inventory_count_events')
    op.drop_index(op.f('ix_inventory_count_events_occurred_at'), table_name='inventory_count_events')
    op.drop_table('inventory_count_events')
    op.drop_index(op.f('ix_inventory_snapshot_items_inventory_campaign_id'), table_name='inventory_snapshot_items')
    op.drop_index('uq_inventory_snapshot_items_campaign_product_location', table_name='inventory_snapshot_items')
    op.drop_index('uq_inventory_snapshot_items_campaign_product_no_location', table_name='inventory_snapshot_items')
    op.drop_table('inventory_snapshot_items')
    op.drop_index(op.f('ix_inventory_recounts_inventory_campaign_id'), table_name='inventory_recounts')
    op.drop_index(op.f('ix_inventory_recounts_assigned_user_id'), table_name='inventory_recounts')
    op.drop_table('inventory_recounts')
    op.drop_index(op.f('ix_inventory_reconciliations_status'), table_name='inventory_reconciliations')
    op.drop_index(op.f('ix_inventory_reconciliations_product_id'), table_name='inventory_reconciliations')
    op.drop_index(op.f('ix_inventory_reconciliations_inventory_campaign_id'), table_name='inventory_reconciliations')
    op.drop_table('inventory_reconciliations')
    op.drop_index(op.f('ix_inventory_count_sessions_user_id'), table_name='inventory_count_sessions')
    op.drop_index(op.f('ix_inventory_count_sessions_inventory_campaign_id'), table_name='inventory_count_sessions')
    op.drop_table('inventory_count_sessions')
    op.drop_index(op.f('ix_inventory_assignments_user_id'), table_name='inventory_assignments')
    op.drop_index(op.f('ix_inventory_assignments_status'), table_name='inventory_assignments')
    op.drop_index(op.f('ix_inventory_assignments_inventory_campaign_id'), table_name='inventory_assignments')
    op.drop_table('inventory_assignments')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_inventory_campaign_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_product_supplier_refs_product_id'), table_name='product_supplier_refs')
    op.drop_index(op.f('ix_product_supplier_refs_contact_id'), table_name='product_supplier_refs')
    op.drop_table('product_supplier_refs')
    op.drop_index(op.f('ix_inventory_campaigns_status'), table_name='inventory_campaigns')
    op.drop_index(op.f('ix_inventory_campaigns_deadline_at'), table_name='inventory_campaigns')
    op.drop_table('inventory_campaigns')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_index(op.f('ix_contacts_external_ref'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
