"""005 import pipeline

Revision ID: ee5e5ebc8e5a
Revises: 004_ensure_enum_checks
Create Date: 2026-09-21 18:41:57.654976

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ee5e5ebc8e5a'
down_revision: str | None = '004_ensure_enum_checks'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('import_type', sa.Enum('CONTACTS', 'PRODUCTS', 'MIXED_PRODUCT_EXPORT', name='importbatchtype', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='importbatchstatus', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_batches_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_import_type'), 'import_batches', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_batches_source_sha256'), 'import_batches', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index('uq_import_batches_type_sha_active', 'import_batches', ['import_type', 'source_sha256'], unique=True, postgresql_where=sa.text("status IN ('PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS')"))
    op.create_table('import_errors',
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_import_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_import_batch_id'), 'import_errors', ['import_batch_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('movement_description', sa.Text(), nullable=True),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('destination_location', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_stock_movements_import_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_import_batch_id'), 'stock_movements', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_table('stock_snapshots',
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'ODOO_EXPORT'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_stock_snapshots_import_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_snapshots_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_snapshots_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_snapshots'))
    )
    op.create_index(op.f('ix_stock_snapshots_import_batch_id'), 'stock_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_stock_snapshots_product_id'), 'stock_snapshots', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_snapshots_product_id'), table_name='stock_snapshots')
    op.drop_index(op.f('ix_stock_snapshots_import_batch_id'), table_name='stock_snapshots')
    op.drop_table('stock_snapshots')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_import_batch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_import_errors_import_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('uq_import_batches_type_sha_active', table_name='import_batches', postgresql_where=sa.text("status IN ('PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS')"))
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_source_sha256'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_import_type'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
